name: conda
channels:
  - anaconda
  - conda-forge
  - pytorch
dependencies:
  - matplotlib=3.7.1
  - pip=23.1.2
  - pip:
    - streamlit==1.20.0
    - torch==2.2.1
    - torchvision==0.17.1
    - Pillow==9.4.0
